name: CI 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: "🧹 Lint & Pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  test:
    name: "🧬 Test & Coverage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: pdm install --dev

      - name: Run pytest with coverage
        run: |
          pdm run pytest --maxfail=1 --disable-warnings --cov=forgesdk --cov-report=xml --cov-report=term-missing
