name: ⚡ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: "🧹 Lint & Pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  test:
    name: "🧪 Test & Coverage"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PDM & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm sync --dev

      - name: Run pytest with coverage
        run: |
          pdm run pytest --maxfail=1 --disable-warnings \
            --cov=forgesdk --cov-report=xml --cov-report=term-missing --cov-report=html > coverage.txt
          cat coverage.txt
          echo "### 🧪 Test & Coverage Summary" >> $GITHUB_STEP_SUMMARY
          tail -n 20 coverage.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload HTML coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
